Ansible 1
Otus-DevOps-2020-02/DmitryKorlas_infra pull request #7
Opened 2020-05-05 23:44 UTC by DmitryKorlas

# Выполнено ДЗ №10

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - added basic inventory configs, describe commands in README.md
 - (task *) used json format for inventory declaration
 - (task **) used dynamic inventory for receiving actual IP addresses from the gcloud

## Как запустить проект:
 run following command in the directory **ansible**
 - to check static inventory: `ansible all -m ping -i inventory.static.json`
 - to check dynamic inventory: `ansible all -m ping`

## Как проверить работоспособность:
 - you have to see success PONG output in the terminal for two hosts

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2020-05-06 06:13 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз. В настройках ansible добавьте обычный инвентарь, в ini формате или в yaml. Запушьте в репо и перезапустите тесты =)

2020-05-06 06:13 UTC, mrgreyves commented on ansible/clone.yml
> +    - name: Clone repo
Вот тут немного съехала секция с тасками =(

2020-05-06 20:31 UTC, DmitryKorlas commented on ansible/clone.yml
> +    - name: Clone repo
мм, не понял что именно съехало, тесты прошли. Добавил разделитель `---` в начале файла

2020-05-07 05:48 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2020-05-07 07:38 UTC, merged